/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package record_management;

import java.awt.Color;
import java.awt.Graphics;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author PRIYAM SHAH
 */
public class Create_Student extends javax.swing.JFrame {

    /**
     * Creates new form Create_Student
     */
    Vector<Student> s;
    public Create_Student(Vector<Student> s) {
        initComponents();
        this.setLocation(500, 200);
        this.s=s;
    }
    public void paint(Graphics g)
    {
         getContentPane().setBackground(Color.WHITE);
         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("NAME");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 0));
        jLabel2.setText("ROLL NUMBER");

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"OOPM", null, null, null},
                {"DATA STRUCTURE", null, null, null},
                {"DD", null, null, null},
                {"DSGT", null, null, null},
                {"COA", null, null, null},
                {"MATHS", null, null, null}
            },
            new String [] {
                "SUBJECT NAME", "UNIT TEST (OUT OF 30)", "ESE (OUT OF 70)", "ATTENDANCE(OUT OF 100)"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setHeaderValue("SUBJECT NAME");
            jTable1.getColumnModel().getColumn(1).setHeaderValue("UNIT TEST (OUT OF 30)");
            jTable1.getColumnModel().getColumn(2).setHeaderValue("ESE (OUT OF 70)");
            jTable1.getColumnModel().getColumn(3).setHeaderValue("ATTENDANCE(OUT OF 100)");
        }

        jButton1.setBackground(new java.awt.Color(255, 153, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 0, 0));
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 102));
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(133, 133, 133)))
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 29, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 918, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(jTextField1.getText().equals("") || jTextField2.getText().equals(""))
            JOptionPane.showMessageDialog(this,"Please fill all data to proceed");
        else
        {
            String a=(String) jTable1.getModel().getValueAt(0,1);
            String b=(String) jTable1.getModel().getValueAt(0,2);
            String c=(String) jTable1.getModel().getValueAt(0,3);
            String d=(String) jTable1.getModel().getValueAt(1,1);
            String e=(String) jTable1.getModel().getValueAt(1,2);
            String f=(String) jTable1.getModel().getValueAt(1,3);
            String g=(String) jTable1.getModel().getValueAt(2,1);
            String h=(String) jTable1.getModel().getValueAt(2,2);
            String i=(String) jTable1.getModel().getValueAt(2,3);
            String j=(String) jTable1.getModel().getValueAt(3,1);
            String k=(String) jTable1.getModel().getValueAt(3,2);
            String l=(String) jTable1.getModel().getValueAt(3,3);
            String m=(String) jTable1.getModel().getValueAt(4,1);
            String n=(String) jTable1.getModel().getValueAt(4,2);
            String o=(String) jTable1.getModel().getValueAt(4,3);
            String p=(String) jTable1.getModel().getValueAt(5,1);
            String q=(String) jTable1.getModel().getValueAt(5,2);
            String r=(String) jTable1.getModel().getValueAt(5,3);
          
          s.add(new Student(jTextField1.getText(),jTextField2.getText(),a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r));
          System.out.println(s);
          
          System.out.println(a+b+c+d+e+f+g+h+i+j+k+l+m+n+o+p+q+r);
          this.dispose();
        }
        /*catch(NullPointerException e)
        {
            JOptionPane.showMessageDialog(this,"SOME FIELDS ARE MISSING");
        }*/
    }//GEN-LAST:event_jButton1ActionPerformed
    class Student
    {
        String Name,Roll;
        String UT_OOPM,UT_DS,UT_DSGT,UT_MATHS,UT_COA,UT_DD,ESE_OOPM,ESE_DS,ESE_DSGT,ESE_MATHS,ESE_COA,ESE_DD,ATT_OOPM,ATT_DS,ATT_DSGT,ATT_MATHS,ATT_COA,ATT_DD;
        Student(String n,String r,String uo ,String eo,String ao,String uds,String eds,String ads,String udd,String edd,String add,String udg,String edg,String adg,String uc,String ec,String  ac,String  um,String  em,String  am)
        {
          Name=n;
          Roll=r;
          UT_OOPM=uo;
          UT_DS=uds;
          UT_DSGT=udg;
          UT_MATHS=um;
          UT_COA=uc;
          UT_DD=udd;
          ESE_OOPM=eo;
          ESE_DS=eds;
          ESE_DSGT=edg;
          ESE_MATHS=em;
          ESE_COA=ec;
          ESE_DD=edd;
          ATT_OOPM=ao;
          ATT_DS=ads;
          ATT_DSGT=adg;
          ATT_MATHS=am;
          ATT_COA=ac;
          ATT_DD=add;
        }
        int getTOTO(){
                return Integer.valueOf(UT_OOPM)+Integer.valueOf(ESE_OOPM) ;
        }
        int getTOTDS(){
                return Integer.valueOf(UT_DS)+Integer.valueOf(ESE_DS) ;
        }
        int getTOTDD(){
                return Integer.valueOf(UT_DD)+Integer.valueOf(ESE_DD) ;
        }
        int getTOTDSGT(){
                return Integer.valueOf(UT_DSGT)+Integer.valueOf(ESE_DSGT) ;
        }
        int getTOTCOA(){
                return Integer.valueOf(UT_COA)+Integer.valueOf(ESE_COA) ;
        }
        int getTOTM(){
                return Integer.valueOf(UT_MATHS)+Integer.valueOf(ESE_MATHS) ;
        }
        
        String getName()
        {
            return Name;
        }
        String getRoll()
        {
            return Roll;
        }
         String getAttendance()
        {
            return ("OOPM: "+ATT_OOPM+"\n"+"DS: " +ATT_DS+" \n"+"DD: "+ATT_DD+"\n "+"DSGT: "+ATT_DSGT+"\n "+"COA: "+ATT_COA+"\n"+"Maths:"+ATT_MATHS);
        }
         String getUTMarks()
         {
             return ("OOPM: "+UT_OOPM+"\n "+"DS: " +UT_DS+"\n "+"DD: "+UT_DD+"\n "+"DSGT: "+UT_DSGT+"\n "+"COA: "+UT_COA+"\n "+"Maths:"+UT_MATHS);
         }
         String getESEMarks()
         {
             return ("OOPM: "+ESE_OOPM+"\n"+"DS: " +ESE_DS+"\n "+"DD: "+ESE_DD+"\n "+"DSGT: "+ESE_DSGT+"\n "+"COA: "+ESE_COA+"\n "+"Maths:"+ESE_MATHS);
         }
         String getATTO()
         {
             return ATT_OOPM;
         }
         String getUTO()
         {
             return UT_OOPM;
         }
         String getESEO()
         {
             return ESE_OOPM;
         }
         String getATTDS()
         {
             return ATT_DS;
         }
          String getUTDS()
         {
             return UT_DS;
         }
         String getESEDS()
         {
             return ESE_DS;
         }
         String getATTDD()
         {
             return ATT_DD;
         }
         String getUTDD()
         {
             return UT_DD;
         }
         String getESEDD()
         {
             return ESE_DD;
         }
         String getATTDSGT()
         {
             return ATT_DSGT;
         }
         
         String getUTDSGT()
         {
             return UT_DSGT;
         }
         String getESEDSGT()
         {
             return ESE_DSGT;
         }
         String getATTCOA()
         {
             return ATT_COA;
         }
          String getUTCOA()
         {
             return UT_COA;
         }
         String getESECOA()
         {
             return ESE_COA;
         }
         String getATTM()
         {
             return ATT_MATHS;
         }
         
          String getUTM()
         {
             return UT_MATHS;
         }
         String getESEM()
         {
             return ESE_MATHS;
         }
         
         public String toString()
         {
             return Name+" "+Roll+" "+UT_OOPM+" "+UT_DS+" "+UT_DD+" "+UT_DSGT+" "+UT_COA+" "+UT_MATHS+" "+ESE_OOPM+" "+ESE_DS+" "+ESE_DD+" "+ESE_DSGT+" "+ESE_COA+" "+ESE_MATHS+" "+ATT_OOPM+" "+ATT_DS+" "+ATT_DD+" "+ATT_DSGT+" "+ATT_COA+" "+ATT_MATHS+" " ;
         }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Create_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Create_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Create_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Create_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Create_Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
